version: 0.2

env:
  variables:
    REPO_NAMESPACE: "sagemaker_endpoint/ollama"
    REPO_TAG: "0.12.5"
  # parameter-store:
    # Optional: Get sensitive configuration from Parameter Store
    # DOCKER_HUB_TOKEN: /codebuild/docker-hub-token

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION:-us-west-2}
      - echo Account is $ACCOUNT, Region is $REGION
      
      # Check and create ECR repository
      - |
        aws ecr describe-repositories --repository-names "${REPO_NAMESPACE}" > /dev/null 2>&1
        if [ $? -ne 0 ]; then
          echo "Creating repository: ${REPO_NAMESPACE}"
          aws ecr create-repository --repository-name "${REPO_NAMESPACE}" > /dev/null
        fi
      
      # Login to ECR
      - |
        if [[ "$REGION" = cn* ]]; then
          aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com.cn
          REPO_NAME="${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com.cn/${REPO_NAMESPACE}:${REPO_TAG}"
        else
          aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com
          REPO_NAME="${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${REPO_NAMESPACE}:${REPO_TAG}"
        fi
      
      - echo Repository name is $REPO_NAME
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for ${DOCKER_PLATFORM:-linux/arm64}...
      - docker build --platform ${DOCKER_PLATFORM:-linux/arm64} --build-arg OLLAMA_VERSION=${REPO_TAG} -t ${REPO_NAMESPACE}:${REPO_TAG} .
      - docker tag ${REPO_NAMESPACE}:${REPO_TAG} $REPO_NAME
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_NAME
      - echo Image pushed successfully
      - echo "Image URI:" $REPO_NAME

artifacts:
  files:
    - '**/*'
  name: ollama-sagemaker-endpoint-build